export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAILURE = "LOGIN_AUTH_FAILURE";
export const REGISTER_AUTH_REQUEST = "REGISTER_AUTH_REQUEST";
export const REGISTER_AUTH_SUCCESS = "REGISTER_AUTH_SUCCESS";
export const REGISTER_AUTH_FAILURE = "REGISTER_AUTH_FAILURE";
